core:
  - all:
      - "**"
      - "!src/**"

lang:en:
  - any:
      - "src/*.md"
      - "src/docs/**/*.md"
      - "src/blog/**/*.md"

lang:ja:
  - any:
      - "src/ja/**/*.md"

lang:zh:
  - any:
      - "src/zh/**/*.md"
