name: CI/CD

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - README.md
  push:
    branches:
      - main
      - "renovate/**"
    paths-ignore:
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  check-typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: crate-ci/typos@master
        with:
          files: .

  textlint:
    name: Textlint
    needs: check-typos
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run textlint:check

  build-and-deploy:
    name: Build and Deploy
    needs: textlint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
        env:
          REDIRECT: true
      - uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
