name: Release

on:
  push:
    branches:
      - release-pr
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
      issue-number:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: oxc-project/oxc
          ref: main
          path: oxc

      - name: Install Tools
        uses: taiki-e/install-action@a86da1a3cb51967612c80d6dc98c5cac03a73025 # v2
        with:
          tool: just

      - run: cd oxc && just website ..
      - run: rm -rf oxc

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run fmt --write ./src/docs/guide/usage/linter

      - uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          commit-message: Release ${{ inputs.version }}
          branch: release
          branch-suffix: timestamp
          title: Release ${{ inputs.version }}
          body: From https://github.com/oxc-project/oxc/pull/${{ inputs.issue-number }}
          assignees: Boshen
          base: main
