name: Release

on:
  push:
    branches:
      - release-pr
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
      issue-number:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: actions/checkout@v4
        with:
          repository: oxc-project/oxc
          ref: main
          path: oxc

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: oxc
          save-if: ${{ github.ref_name == 'main' }}

      - name: Install Tools
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - run: cd oxc && just website ..
      - run: rm -rf oxc

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run fmt --write ./src/docs/guide/usage/linter

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          commit-message: Release ${{ inputs.version }}
          branch: release
          branch-suffix: timestamp
          title: Release ${{ inputs.version }}
          body: From https://github.com/oxc-project/oxc/pull/${{ inputs.issue-number }}
          assignees: Boshen
          base: main
